language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "pypy"
    - python: "2.6"
  allow_failures:
    - python: "2.6"
    - python: "pypy"

script: ./test.py $TEST_SUITE

sudo: false

install:
  - "pip install pep8"
  - "pip install nose==1.3.7"
  - "python setup.py install"

script:
  - pep8 setup.py tilepaper/ tests/ --statistics
  - mkdir test-output
  - tilepaper --source=./example-images/ --destination=test-output/ --config=./example-config.yml --verbose
  - nosetests -v
