language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.3"
    - python: "3.4"
    - python: "3.5"
    - python: "3.5-dev"
    - python: "nightly"
    - python: "pypy"
    - python: "2.6"
  allow_failures:
    - python: "2.6"
    - python: "pypy"
    - python: "3.5-dev"
    - python: "nightly"

script: ./test.py $TEST_SUITE

sudo: false

install:
  - "pip install codecov"
  - "pip install pep8"
  - "pip install flake8==2.4.1"
  - "pip install nose==1.3.7"
  - "python setup.py install"

script:
  - pep8 setup.py tilepaper/ tests/ --statistics
  - flake8 setup.py tilepaper/ tests/ --statistics
  - mkdir test-output
  - tilepaper --source=./example-images/ --destination=test-output/ --config=./example-config.yml --verbose
  - nosetests -v tests/testTiler.py:testTiler.test_fullProcess
  - nosetests -v --exclude=test_fullProcess --with-coverage --cover-package=tilepaper

after_success:
  - codecov
